<?php
/**
 * BankingPermissions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cyclos\Api\Model;

use \ArrayAccess;
use \Cyclos\Api\ObjectSerializer;

/**
 * BankingPermissions Class Doc Comment
 *
 * @category Class
 * @description Permissions for banking
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BankingPermissions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BankingPermissions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accounts' => '\Cyclos\Api\Model\AccountPermissions[]',
'payments' => 'AllOfBankingPermissionsPayments',
'authorizations' => 'AllOfBankingPermissionsAuthorizations',
'scheduled_payments' => 'AllOfBankingPermissionsScheduledPayments',
'recurring_payments' => 'AllOfBankingPermissionsRecurringPayments',
'external_payments' => 'AllOfBankingPermissionsExternalPayments',
'payment_requests' => 'AllOfBankingPermissionsPaymentRequests',
'tickets' => 'AllOfBankingPermissionsTickets',
'search_general_transfers' => 'bool',
'search_users_with_balances' => 'bool',
'search_general_balance_limits' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accounts' => null,
'payments' => null,
'authorizations' => null,
'scheduled_payments' => null,
'recurring_payments' => null,
'external_payments' => null,
'payment_requests' => null,
'tickets' => null,
'search_general_transfers' => null,
'search_users_with_balances' => null,
'search_general_balance_limits' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accounts' => 'accounts',
'payments' => 'payments',
'authorizations' => 'authorizations',
'scheduled_payments' => 'scheduledPayments',
'recurring_payments' => 'recurringPayments',
'external_payments' => 'externalPayments',
'payment_requests' => 'paymentRequests',
'tickets' => 'tickets',
'search_general_transfers' => 'searchGeneralTransfers',
'search_users_with_balances' => 'searchUsersWithBalances',
'search_general_balance_limits' => 'searchGeneralBalanceLimits'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accounts' => 'setAccounts',
'payments' => 'setPayments',
'authorizations' => 'setAuthorizations',
'scheduled_payments' => 'setScheduledPayments',
'recurring_payments' => 'setRecurringPayments',
'external_payments' => 'setExternalPayments',
'payment_requests' => 'setPaymentRequests',
'tickets' => 'setTickets',
'search_general_transfers' => 'setSearchGeneralTransfers',
'search_users_with_balances' => 'setSearchUsersWithBalances',
'search_general_balance_limits' => 'setSearchGeneralBalanceLimits'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accounts' => 'getAccounts',
'payments' => 'getPayments',
'authorizations' => 'getAuthorizations',
'scheduled_payments' => 'getScheduledPayments',
'recurring_payments' => 'getRecurringPayments',
'external_payments' => 'getExternalPayments',
'payment_requests' => 'getPaymentRequests',
'tickets' => 'getTickets',
'search_general_transfers' => 'getSearchGeneralTransfers',
'search_users_with_balances' => 'getSearchUsersWithBalances',
'search_general_balance_limits' => 'getSearchGeneralBalanceLimits'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accounts'] = isset($data['accounts']) ? $data['accounts'] : null;
        $this->container['payments'] = isset($data['payments']) ? $data['payments'] : null;
        $this->container['authorizations'] = isset($data['authorizations']) ? $data['authorizations'] : null;
        $this->container['scheduled_payments'] = isset($data['scheduled_payments']) ? $data['scheduled_payments'] : null;
        $this->container['recurring_payments'] = isset($data['recurring_payments']) ? $data['recurring_payments'] : null;
        $this->container['external_payments'] = isset($data['external_payments']) ? $data['external_payments'] : null;
        $this->container['payment_requests'] = isset($data['payment_requests']) ? $data['payment_requests'] : null;
        $this->container['tickets'] = isset($data['tickets']) ? $data['tickets'] : null;
        $this->container['search_general_transfers'] = isset($data['search_general_transfers']) ? $data['search_general_transfers'] : null;
        $this->container['search_users_with_balances'] = isset($data['search_users_with_balances']) ? $data['search_users_with_balances'] : null;
        $this->container['search_general_balance_limits'] = isset($data['search_general_balance_limits']) ? $data['search_general_balance_limits'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accounts
     *
     * @return \Cyclos\Api\Model\AccountPermissions[]
     */
    public function getAccounts()
    {
        return $this->container['accounts'];
    }

    /**
     * Sets accounts
     *
     * @param \Cyclos\Api\Model\AccountPermissions[] $accounts Permissions over each owned account
     *
     * @return $this
     */
    public function setAccounts($accounts)
    {
        $this->container['accounts'] = $accounts;

        return $this;
    }

    /**
     * Gets payments
     *
     * @return AllOfBankingPermissionsPayments
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     *
     * @param AllOfBankingPermissionsPayments $payments Payments permissions
     *
     * @return $this
     */
    public function setPayments($payments)
    {
        $this->container['payments'] = $payments;

        return $this;
    }

    /**
     * Gets authorizations
     *
     * @return AllOfBankingPermissionsAuthorizations
     */
    public function getAuthorizations()
    {
        return $this->container['authorizations'];
    }

    /**
     * Sets authorizations
     *
     * @param AllOfBankingPermissionsAuthorizations $authorizations Transaction authorization permissions
     *
     * @return $this
     */
    public function setAuthorizations($authorizations)
    {
        $this->container['authorizations'] = $authorizations;

        return $this;
    }

    /**
     * Gets scheduled_payments
     *
     * @return AllOfBankingPermissionsScheduledPayments
     */
    public function getScheduledPayments()
    {
        return $this->container['scheduled_payments'];
    }

    /**
     * Sets scheduled_payments
     *
     * @param AllOfBankingPermissionsScheduledPayments $scheduled_payments Scheduled payments permissions
     *
     * @return $this
     */
    public function setScheduledPayments($scheduled_payments)
    {
        $this->container['scheduled_payments'] = $scheduled_payments;

        return $this;
    }

    /**
     * Gets recurring_payments
     *
     * @return AllOfBankingPermissionsRecurringPayments
     */
    public function getRecurringPayments()
    {
        return $this->container['recurring_payments'];
    }

    /**
     * Sets recurring_payments
     *
     * @param AllOfBankingPermissionsRecurringPayments $recurring_payments Recurring payments permissions
     *
     * @return $this
     */
    public function setRecurringPayments($recurring_payments)
    {
        $this->container['recurring_payments'] = $recurring_payments;

        return $this;
    }

    /**
     * Gets external_payments
     *
     * @return AllOfBankingPermissionsExternalPayments
     */
    public function getExternalPayments()
    {
        return $this->container['external_payments'];
    }

    /**
     * Sets external_payments
     *
     * @param AllOfBankingPermissionsExternalPayments $external_payments External payments permissions
     *
     * @return $this
     */
    public function setExternalPayments($external_payments)
    {
        $this->container['external_payments'] = $external_payments;

        return $this;
    }

    /**
     * Gets payment_requests
     *
     * @return AllOfBankingPermissionsPaymentRequests
     */
    public function getPaymentRequests()
    {
        return $this->container['payment_requests'];
    }

    /**
     * Sets payment_requests
     *
     * @param AllOfBankingPermissionsPaymentRequests $payment_requests Payment requests permissions
     *
     * @return $this
     */
    public function setPaymentRequests($payment_requests)
    {
        $this->container['payment_requests'] = $payment_requests;

        return $this;
    }

    /**
     * Gets tickets
     *
     * @return AllOfBankingPermissionsTickets
     */
    public function getTickets()
    {
        return $this->container['tickets'];
    }

    /**
     * Sets tickets
     *
     * @param AllOfBankingPermissionsTickets $tickets Tickets permissions
     *
     * @return $this
     */
    public function setTickets($tickets)
    {
        $this->container['tickets'] = $tickets;

        return $this;
    }

    /**
     * Gets search_general_transfers
     *
     * @return bool
     */
    public function getSearchGeneralTransfers()
    {
        return $this->container['search_general_transfers'];
    }

    /**
     * Sets search_general_transfers
     *
     * @param bool $search_general_transfers Can the authenticated admin / broker perform a general transfers search (all visible transfers, regardless of the user / account)?
     *
     * @return $this
     */
    public function setSearchGeneralTransfers($search_general_transfers)
    {
        $this->container['search_general_transfers'] = $search_general_transfers;

        return $this;
    }

    /**
     * Gets search_users_with_balances
     *
     * @return bool
     */
    public function getSearchUsersWithBalances()
    {
        return $this->container['search_users_with_balances'];
    }

    /**
     * Sets search_users_with_balances
     *
     * @param bool $search_users_with_balances Can the authenticated admin / broker search managed users together with their account balances?
     *
     * @return $this
     */
    public function setSearchUsersWithBalances($search_users_with_balances)
    {
        $this->container['search_users_with_balances'] = $search_users_with_balances;

        return $this;
    }

    /**
     * Gets search_general_balance_limits
     *
     * @return bool
     */
    public function getSearchGeneralBalanceLimits()
    {
        return $this->container['search_general_balance_limits'];
    }

    /**
     * Sets search_general_balance_limits
     *
     * @param bool $search_general_balance_limits Can the authenticated admin / broker perform a general account balance limit search, for all visible accounts?
     *
     * @return $this
     */
    public function setSearchGeneralBalanceLimits($search_general_balance_limits)
    {
        $this->container['search_general_balance_limits'] = $search_general_balance_limits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
