<?php
/**
 * ContactListDataForSearch
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cyclos\Api\Model;

use \ArrayAccess;
use \Cyclos\Api\ObjectSerializer;

/**
 * ContactListDataForSearch Class Doc Comment
 *
 * @category Class
 * @description Data for searching an user&#x27;s contact list
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactListDataForSearch implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ContactListDataForSearch';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'user' => '\Cyclos\Api\Model\User',
'custom_fields' => '\Cyclos\Api\Model\CustomFieldDetailed[]',
'fields_in_search' => 'string[]',
'fields_in_list' => 'string[]',
'query' => 'AllOfContactListDataForSearchQuery',
'has_visible_fields' => 'bool',
'has_editable_fields' => 'bool',
'address_fields_in_search' => '\Cyclos\Api\Model\AddressQueryFieldEnum[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'user' => null,
'custom_fields' => null,
'fields_in_search' => null,
'fields_in_list' => null,
'query' => null,
'has_visible_fields' => null,
'has_editable_fields' => null,
'address_fields_in_search' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'user' => 'user',
'custom_fields' => 'customFields',
'fields_in_search' => 'fieldsInSearch',
'fields_in_list' => 'fieldsInList',
'query' => 'query',
'has_visible_fields' => 'hasVisibleFields',
'has_editable_fields' => 'hasEditableFields',
'address_fields_in_search' => 'addressFieldsInSearch'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'user' => 'setUser',
'custom_fields' => 'setCustomFields',
'fields_in_search' => 'setFieldsInSearch',
'fields_in_list' => 'setFieldsInList',
'query' => 'setQuery',
'has_visible_fields' => 'setHasVisibleFields',
'has_editable_fields' => 'setHasEditableFields',
'address_fields_in_search' => 'setAddressFieldsInSearch'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'user' => 'getUser',
'custom_fields' => 'getCustomFields',
'fields_in_search' => 'getFieldsInSearch',
'fields_in_list' => 'getFieldsInList',
'query' => 'getQuery',
'has_visible_fields' => 'getHasVisibleFields',
'has_editable_fields' => 'getHasEditableFields',
'address_fields_in_search' => 'getAddressFieldsInSearch'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['user'] = isset($data['user']) ? $data['user'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
        $this->container['fields_in_search'] = isset($data['fields_in_search']) ? $data['fields_in_search'] : null;
        $this->container['fields_in_list'] = isset($data['fields_in_list']) ? $data['fields_in_list'] : null;
        $this->container['query'] = isset($data['query']) ? $data['query'] : null;
        $this->container['has_visible_fields'] = isset($data['has_visible_fields']) ? $data['has_visible_fields'] : null;
        $this->container['has_editable_fields'] = isset($data['has_editable_fields']) ? $data['has_editable_fields'] : null;
        $this->container['address_fields_in_search'] = isset($data['address_fields_in_search']) ? $data['address_fields_in_search'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets user
     *
     * @return \Cyclos\Api\Model\User
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \Cyclos\Api\Model\User $user user
     *
     * @return $this
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return \Cyclos\Api\Model\CustomFieldDetailed[]
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param \Cyclos\Api\Model\CustomFieldDetailed[] $custom_fields The list of contact custom fields that are either to be used as search filter (if its internal name is present on `fieldsInSearch`) and / or in the result list (if its internal name is present on `fieldsInList`)
     *
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets fields_in_search
     *
     * @return string[]
     */
    public function getFieldsInSearch()
    {
        return $this->container['fields_in_search'];
    }

    /**
     * Sets fields_in_search
     *
     * @param string[] $fields_in_search The internal names of the contact custom fields that should be used as search filters (separated fields, not keywords)
     *
     * @return $this
     */
    public function setFieldsInSearch($fields_in_search)
    {
        $this->container['fields_in_search'] = $fields_in_search;

        return $this;
    }

    /**
     * Gets fields_in_list
     *
     * @return string[]
     */
    public function getFieldsInList()
    {
        return $this->container['fields_in_list'];
    }

    /**
     * Sets fields_in_list
     *
     * @param string[] $fields_in_list The internal names of the contact custom fields that will be returned together with each record, and should be shown in the result list
     *
     * @return $this
     */
    public function setFieldsInList($fields_in_list)
    {
        $this->container['fields_in_list'] = $fields_in_list;

        return $this;
    }

    /**
     * Gets query
     *
     * @return AllOfContactListDataForSearchQuery
     */
    public function getQuery()
    {
        return $this->container['query'];
    }

    /**
     * Sets query
     *
     * @param AllOfContactListDataForSearchQuery $query Default query filters for searching records
     *
     * @return $this
     */
    public function setQuery($query)
    {
        $this->container['query'] = $query;

        return $this;
    }

    /**
     * Gets has_visible_fields
     *
     * @return bool
     */
    public function getHasVisibleFields()
    {
        return $this->container['has_visible_fields'];
    }

    /**
     * Sets has_visible_fields
     *
     * @param bool $has_visible_fields This flag can be used to know whether selecting a contact in the contact list should show direclty the user profile or a contact details page to show additional custom fields.
     *
     * @return $this
     */
    public function setHasVisibleFields($has_visible_fields)
    {
        $this->container['has_visible_fields'] = $has_visible_fields;

        return $this;
    }

    /**
     * Gets has_editable_fields
     *
     * @return bool
     */
    public function getHasEditableFields()
    {
        return $this->container['has_editable_fields'];
    }

    /**
     * Sets has_editable_fields
     *
     * @param bool $has_editable_fields This flag can be used to know whether the contact should be added directly to the user's contact list or a page should be shown for the user to fill in the contact custom fields.
     *
     * @return $this
     */
    public function setHasEditableFields($has_editable_fields)
    {
        $this->container['has_editable_fields'] = $has_editable_fields;

        return $this;
    }

    /**
     * Gets address_fields_in_search
     *
     * @return \Cyclos\Api\Model\AddressQueryFieldEnum[]
     */
    public function getAddressFieldsInSearch()
    {
        return $this->container['address_fields_in_search'];
    }

    /**
     * Sets address_fields_in_search
     *
     * @param \Cyclos\Api\Model\AddressQueryFieldEnum[] $address_fields_in_search address_fields_in_search
     *
     * @return $this
     */
    public function setAddressFieldsInSearch($address_fields_in_search)
    {
        $this->container['address_fields_in_search'] = $address_fields_in_search;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
