<?php
/**
 * NotificationEntityTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cyclos\Api\Model;
use \Cyclos\Api\ObjectSerializer;

/**
 * NotificationEntityTypeEnum Class Doc Comment
 *
 * @category Class
 * @description The type of the entity referenced by the notification, if any. Possible values are: - &#x60;adQuestion&#x60;: The entity is an advertisement question - &#x60;errorLog&#x60;: The entity is an error log - &#x60;feedback&#x60;: The entity is a transaction feedback - &#x60;installment&#x60;: The entity is a scheduled payment installment - &#x60;marketplace&#x60;: The entity is a &#x60;simple&#x60; or &#x60;webshop&#x60; advertisement - &#x60;network&#x60;: The entity is a network - &#x60;occurrence&#x60;: The entity is a failed occurrence of a recurring payment - &#x60;order&#x60;: The entity is an order - &#x60;passwordType&#x60;: The entity is a password type - &#x60;reference&#x60;: The entity is an user reference - &#x60;systemAlert&#x60;: The entity is a system alert - &#x60;token&#x60;: The entity is a token (user identification) - &#x60;transaction&#x60;: The entity is a transaction - &#x60;transfer&#x60;: The entity is a transfer - &#x60;user&#x60;: The entity is an user - &#x60;userAlert&#x60;: The entity is an user alert - &#x60;userImportedFile&#x60;: The entity is an user imported file - &#x60;voucher&#x60;: The entity is a voucher - &#x60;voucherType&#x60;: The entity is a voucher type
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NotificationEntityTypeEnum
{
    /**
     * Possible values of this enum
     */
    const AD_QUESTION = 'adQuestion';
const ERROR_LOG = 'errorLog';
const FEEDBACK = 'feedback';
const INSTALLMENT = 'installment';
const MARKETPLACE = 'marketplace';
const NETWORK = 'network';
const OCCURRENCE = 'occurrence';
const ORDER = 'order';
const PASSWORD_TYPE = 'passwordType';
const REFERENCE = 'reference';
const SYSTEM_ALERT = 'systemAlert';
const TOKEN = 'token';
const TRANSACTION = 'transaction';
const TRANSFER = 'transfer';
const USER = 'user';
const USER_ALERT = 'userAlert';
const USER_IMPORTED_FILE = 'userImportedFile';
const VOUCHER = 'voucher';
const VOUCHER_TYPE = 'voucherType';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AD_QUESTION,
self::ERROR_LOG,
self::FEEDBACK,
self::INSTALLMENT,
self::MARKETPLACE,
self::NETWORK,
self::OCCURRENCE,
self::ORDER,
self::PASSWORD_TYPE,
self::REFERENCE,
self::SYSTEM_ALERT,
self::TOKEN,
self::TRANSACTION,
self::TRANSFER,
self::USER,
self::USER_ALERT,
self::USER_IMPORTED_FILE,
self::VOUCHER,
self::VOUCHER_TYPE,        ];
    }
}
