<?php
/**
 * UnauthorizedError
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cyclos\Api\Model;

use \ArrayAccess;
use \Cyclos\Api\ObjectSerializer;

/**
 * UnauthorizedError Class Doc Comment
 *
 * @category Class
 * @description Error returned when a HTTP status code 401 occurs
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UnauthorizedError implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UnauthorizedError';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'missing_secondary_password' => 'AllOfUnauthorizedErrorMissingSecondaryPassword',
'secondary_device_allowed' => 'bool',
'code' => '\Cyclos\Api\Model\UnauthorizedErrorCode',
'user_status' => 'AllOfUnauthorizedErrorUserStatus',
'password_status' => 'AllOfUnauthorizedErrorPasswordStatus'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'missing_secondary_password' => null,
'secondary_device_allowed' => null,
'code' => null,
'user_status' => null,
'password_status' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'missing_secondary_password' => 'missingSecondaryPassword',
'secondary_device_allowed' => 'secondaryDeviceAllowed',
'code' => 'code',
'user_status' => 'userStatus',
'password_status' => 'passwordStatus'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'missing_secondary_password' => 'setMissingSecondaryPassword',
'secondary_device_allowed' => 'setSecondaryDeviceAllowed',
'code' => 'setCode',
'user_status' => 'setUserStatus',
'password_status' => 'setPasswordStatus'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'missing_secondary_password' => 'getMissingSecondaryPassword',
'secondary_device_allowed' => 'getSecondaryDeviceAllowed',
'code' => 'getCode',
'user_status' => 'getUserStatus',
'password_status' => 'getPasswordStatus'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['missing_secondary_password'] = isset($data['missing_secondary_password']) ? $data['missing_secondary_password'] : null;
        $this->container['secondary_device_allowed'] = isset($data['secondary_device_allowed']) ? $data['secondary_device_allowed'] : null;
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['user_status'] = isset($data['user_status']) ? $data['user_status'] : null;
        $this->container['password_status'] = isset($data['password_status']) ? $data['password_status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets missing_secondary_password
     *
     * @return AllOfUnauthorizedErrorMissingSecondaryPassword
     */
    public function getMissingSecondaryPassword()
    {
        return $this->container['missing_secondary_password'];
    }

    /**
     * Sets missing_secondary_password
     *
     * @param AllOfUnauthorizedErrorMissingSecondaryPassword $missing_secondary_password May only returned when `code` is `login` and there is a login confirmation with password defined for the channel.
     *
     * @return $this
     */
    public function setMissingSecondaryPassword($missing_secondary_password)
    {
        $this->container['missing_secondary_password'] = $missing_secondary_password;

        return $this;
    }

    /**
     * Gets secondary_device_allowed
     *
     * @return bool
     */
    public function getSecondaryDeviceAllowed()
    {
        return $this->container['secondary_device_allowed'];
    }

    /**
     * Sets secondary_device_allowed
     *
     * @param bool $secondary_device_allowed Whether confirmations with device are allowed or not.   May only returned when `code` is `login` and there is a login confirmation defined for the channel.
     *
     * @return $this
     */
    public function setSecondaryDeviceAllowed($secondary_device_allowed)
    {
        $this->container['secondary_device_allowed'] = $secondary_device_allowed;

        return $this;
    }

    /**
     * Gets code
     *
     * @return \Cyclos\Api\Model\UnauthorizedErrorCode
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param \Cyclos\Api\Model\UnauthorizedErrorCode $code code
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets user_status
     *
     * @return AllOfUnauthorizedErrorUserStatus
     */
    public function getUserStatus()
    {
        return $this->container['user_status'];
    }

    /**
     * Sets user_status
     *
     * @param AllOfUnauthorizedErrorUserStatus $user_status May only returned when `code` is `login`.
     *
     * @return $this
     */
    public function setUserStatus($user_status)
    {
        $this->container['user_status'] = $user_status;

        return $this;
    }

    /**
     * Gets password_status
     *
     * @return AllOfUnauthorizedErrorPasswordStatus
     */
    public function getPasswordStatus()
    {
        return $this->container['password_status'];
    }

    /**
     * Sets password_status
     *
     * @param AllOfUnauthorizedErrorPasswordStatus $password_status May only returned when `code` is `login`.
     *
     * @return $this
     */
    public function setPasswordStatus($password_status)
    {
        $this->container['password_status'] = $password_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
