<?php
/**
 * UserPaymentPermissions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cyclos\Api\Model;

use \ArrayAccess;
use \Cyclos\Api\ObjectSerializer;

/**
 * UserPaymentPermissions Class Doc Comment
 *
 * @category Class
 * @description Permissions for payments regarding a user
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserPaymentPermissions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UserPaymentPermissions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'as_user_to_self' => 'bool',
'as_user_to_system' => 'bool',
'as_user_to_user' => 'bool',
'system_to_user' => 'bool',
'user_to_user' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'as_user_to_self' => null,
'as_user_to_system' => null,
'as_user_to_user' => null,
'system_to_user' => null,
'user_to_user' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'as_user_to_self' => 'asUserToSelf',
'as_user_to_system' => 'asUserToSystem',
'as_user_to_user' => 'asUserToUser',
'system_to_user' => 'systemToUser',
'user_to_user' => 'userToUser'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'as_user_to_self' => 'setAsUserToSelf',
'as_user_to_system' => 'setAsUserToSystem',
'as_user_to_user' => 'setAsUserToUser',
'system_to_user' => 'setSystemToUser',
'user_to_user' => 'setUserToUser'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'as_user_to_self' => 'getAsUserToSelf',
'as_user_to_system' => 'getAsUserToSystem',
'as_user_to_user' => 'getAsUserToUser',
'system_to_user' => 'getSystemToUser',
'user_to_user' => 'getUserToUser'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['as_user_to_self'] = isset($data['as_user_to_self']) ? $data['as_user_to_self'] : null;
        $this->container['as_user_to_system'] = isset($data['as_user_to_system']) ? $data['as_user_to_system'] : null;
        $this->container['as_user_to_user'] = isset($data['as_user_to_user']) ? $data['as_user_to_user'] : null;
        $this->container['system_to_user'] = isset($data['system_to_user']) ? $data['system_to_user'] : null;
        $this->container['user_to_user'] = isset($data['user_to_user']) ? $data['user_to_user'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets as_user_to_self
     *
     * @return bool
     */
    public function getAsUserToSelf()
    {
        return $this->container['as_user_to_self'];
    }

    /**
     * Sets as_user_to_self
     *
     * @param bool $as_user_to_self Can the authenticated administrator or broker perform a payment in behalf of this user to another account belonging to the same user?
     *
     * @return $this
     */
    public function setAsUserToSelf($as_user_to_self)
    {
        $this->container['as_user_to_self'] = $as_user_to_self;

        return $this;
    }

    /**
     * Gets as_user_to_system
     *
     * @return bool
     */
    public function getAsUserToSystem()
    {
        return $this->container['as_user_to_system'];
    }

    /**
     * Sets as_user_to_system
     *
     * @param bool $as_user_to_system Can the authenticated administrator or broker perform a payment in behalf of this user to a system account?
     *
     * @return $this
     */
    public function setAsUserToSystem($as_user_to_system)
    {
        $this->container['as_user_to_system'] = $as_user_to_system;

        return $this;
    }

    /**
     * Gets as_user_to_user
     *
     * @return bool
     */
    public function getAsUserToUser()
    {
        return $this->container['as_user_to_user'];
    }

    /**
     * Sets as_user_to_user
     *
     * @param bool $as_user_to_user Can the authenticated administrator or broker perform a payment in behalf of this user to another user?
     *
     * @return $this
     */
    public function setAsUserToUser($as_user_to_user)
    {
        $this->container['as_user_to_user'] = $as_user_to_user;

        return $this;
    }

    /**
     * Gets system_to_user
     *
     * @return bool
     */
    public function getSystemToUser()
    {
        return $this->container['system_to_user'];
    }

    /**
     * Sets system_to_user
     *
     * @param bool $system_to_user Can the authenticated administrator perform a payment from a system account to this user?
     *
     * @return $this
     */
    public function setSystemToUser($system_to_user)
    {
        $this->container['system_to_user'] = $system_to_user;

        return $this;
    }

    /**
     * Gets user_to_user
     *
     * @return bool
     */
    public function getUserToUser()
    {
        return $this->container['user_to_user'];
    }

    /**
     * Sets user_to_user
     *
     * @param bool $user_to_user Can the authenticated member perform a payment from an himself to this user?
     *
     * @return $this
     */
    public function setUserToUser($user_to_user)
    {
        $this->container['user_to_user'] = $user_to_user;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
