<?php
/**
 * UserValidationPermissions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cyclos\Api\Model;

use \ArrayAccess;
use \Cyclos\Api\ObjectSerializer;

/**
 * UserValidationPermissions Class Doc Comment
 *
 * @category Class
 * @description Permissions over the registration / email change validations of a given user
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserValidationPermissions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UserValidationPermissions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'validate_registration' => 'bool',
'resend_registration_validation' => 'bool',
'validate_email_change' => 'bool',
'resend_email_change' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'validate_registration' => null,
'resend_registration_validation' => null,
'validate_email_change' => null,
'resend_email_change' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'validate_registration' => 'validateRegistration',
'resend_registration_validation' => 'resendRegistrationValidation',
'validate_email_change' => 'validateEmailChange',
'resend_email_change' => 'resendEmailChange'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'validate_registration' => 'setValidateRegistration',
'resend_registration_validation' => 'setResendRegistrationValidation',
'validate_email_change' => 'setValidateEmailChange',
'resend_email_change' => 'setResendEmailChange'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'validate_registration' => 'getValidateRegistration',
'resend_registration_validation' => 'getResendRegistrationValidation',
'validate_email_change' => 'getValidateEmailChange',
'resend_email_change' => 'getResendEmailChange'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['validate_registration'] = isset($data['validate_registration']) ? $data['validate_registration'] : null;
        $this->container['resend_registration_validation'] = isset($data['resend_registration_validation']) ? $data['resend_registration_validation'] : null;
        $this->container['validate_email_change'] = isset($data['validate_email_change']) ? $data['validate_email_change'] : null;
        $this->container['resend_email_change'] = isset($data['resend_email_change']) ? $data['resend_email_change'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets validate_registration
     *
     * @return bool
     */
    public function getValidateRegistration()
    {
        return $this->container['validate_registration'];
    }

    /**
     * Sets validate_registration
     *
     * @param bool $validate_registration Can the authenticated administrator or broker manually mark a pending user as validated?
     *
     * @return $this
     */
    public function setValidateRegistration($validate_registration)
    {
        $this->container['validate_registration'] = $validate_registration;

        return $this;
    }

    /**
     * Gets resend_registration_validation
     *
     * @return bool
     */
    public function getResendRegistrationValidation()
    {
        return $this->container['resend_registration_validation'];
    }

    /**
     * Sets resend_registration_validation
     *
     * @param bool $resend_registration_validation Can the authenticated administrator or broker re-send the e-mail to confirm the registration of the given user?
     *
     * @return $this
     */
    public function setResendRegistrationValidation($resend_registration_validation)
    {
        $this->container['resend_registration_validation'] = $resend_registration_validation;

        return $this;
    }

    /**
     * Gets validate_email_change
     *
     * @return bool
     */
    public function getValidateEmailChange()
    {
        return $this->container['validate_email_change'];
    }

    /**
     * Sets validate_email_change
     *
     * @param bool $validate_email_change Can the authenticated administrator or broker manually mark a pending e-mail change as validated for the given user?
     *
     * @return $this
     */
    public function setValidateEmailChange($validate_email_change)
    {
        $this->container['validate_email_change'] = $validate_email_change;

        return $this;
    }

    /**
     * Gets resend_email_change
     *
     * @return bool
     */
    public function getResendEmailChange()
    {
        return $this->container['resend_email_change'];
    }

    /**
     * Sets resend_email_change
     *
     * @param bool $resend_email_change Can the authenticated administrator or broker re-send the e-mail to confirm the e-mail change of the given user?
     *
     * @return $this
     */
    public function setResendEmailChange($resend_email_change)
    {
        $this->container['resend_email_change'] = $resend_email_change;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
