version: '3'
services:
  cra-php:
    build: php
    container_name: cra-php
    volumes:
      # /projects muss in der Virtualbox als Shared Folder gemounted sein
      - /projects/CyclosRestAPI/:/srv/api
    extra_hosts:
      - host.vbox.internal:192.168.56.1 # IP des VM bridge adapters