version: '3'
services:
  cra-php:
    build: php
    container_name: cra-php
    volumes:
      - ../:/var/www/html
    ports:
      - 10000:9000
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal