<?php
/**
 * BaseCustomFieldValueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cyclos\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cyclos 4.12.6 API
 *
 * The Cyclos REST API is described using OpenAPI 3.0. The descriptor for the api can be downloaded in both [YAML](http://kb1.cyclos-dev.info/api/cyclos-openapi.yaml) or [JSON](http://kb1.cyclos-dev.info/api/cyclos-openapi.json) formats. These files can be used in tools that support the OpenAPI specification, such as the [Swagger Generator](https://generator.swagger.io/).  In the API, whenever some data is referenced, for example, a group, or payment type, either id or internal name can be used. When an user is to be referenced, the special word 'self' (sans quotes) always refers to the currently authenticated user, and any identification method (login name, e-mail, mobile phone, account number or custom field) that can be used on keywords search (as configured in the products) can also be used to identify users. Some specific data types have other identification fields, like accounts can have a number and payments can have a transaction number. This all depends on the current configuration.  Most of the operations that return data allow selecting which fields to include in the response. This is useful for reducing the data to be download over the network. If nothing is set, all object fields are returned. Unprefixed field names will be handled like a whitelist (only listed fields will be included), while names starting with a minus (-) or exclamation mark (!) will be handled as blacklist (listed fields will not be included). This works for nesting as well. For example: `a,b.b1,c.-c1,c.-c2` will return the fields `a`, `b` (containing only the `b1` field) and `c` (containing all its fields except for `c1` or `c2`).  For details of the deprecated elements (operations and model) please visit the [deprecation notes page](https://documentation.cyclos.org/4.12.6/api-deprecation.html) for this version.
 *
 * OpenAPI spec version: 4.12.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Cyclos\Api;

/**
 * BaseCustomFieldValueTest Class Doc Comment
 *
 * @category    Class
 * @description Holds detailed information about a custom field value. The actual value should be read from a property depending on the field type:   - If the type is either &#x60;string&#x60;,   &#x60;text&#x60;,   &#x60;richText&#x60; or   &#x60;url&#x60;, the property is on &#x60;stringValue&#x60;;   - If the type is &#x60;integer&#x60;, the property is   &#x60;integerValue&#x60;; - If the type is &#x60;decimal&#x60;,   the property is &#x60;decimalValue&#x60;;   - If the type is &#x60;date&#x60;, the property is   &#x60;dateValue&#x60;; - If the type is &#x60;boolean&#x60;, the property is &#x60;booleanValue&#x60;;  - If the type is either &#x60;singleSelection&#x60; or   &#x60;multiSelection&#x60;, the property is   &#x60;possibleValues&#x60;;   - If the type is &#x60;dynamicSelection&#x60;, the   property is &#x60;dynamicValue&#x60;;   - If the type is &#x60;file&#x60;, the property is   &#x60;fileValues&#x60;;   - If the type is &#x60;image&#x60;, the property is   &#x60;imageValues&#x60;;   - Finally, if the type is &#x60;linkedEntity&#x60;, it   depends on the value of the field&#x27;s &#x60;linkedEntityType&#x60;:     - If the entity type is &#x60;user&#x60;, the property     is &#x60;userValue&#x60;;     - If the entity type is &#x60;record&#x60;, the     property is &#x60;recordValue&#x60;;     - If the entity type is &#x60;transaction&#x60;, the     property is &#x60;transactionValue&#x60;;     - If the entity type is &#x60;transfer&#x60;, the     property is &#x60;transferValue&#x60;;     - If the entity type is &#x60;advertisement&#x60;, the     property is &#x60;adValue&#x60;.
 * @package     Cyclos\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BaseCustomFieldValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BaseCustomFieldValue"
     */
    public function testBaseCustomFieldValue()
    {
    }

    /**
     * Test attribute "string_value"
     */
    public function testPropertyStringValue()
    {
    }

    /**
     * Test attribute "date_value"
     */
    public function testPropertyDateValue()
    {
    }

    /**
     * Test attribute "boolean_value"
     */
    public function testPropertyBooleanValue()
    {
    }

    /**
     * Test attribute "integer_value"
     */
    public function testPropertyIntegerValue()
    {
    }

    /**
     * Test attribute "decimal_value"
     */
    public function testPropertyDecimalValue()
    {
    }

    /**
     * Test attribute "enumerated_values"
     */
    public function testPropertyEnumeratedValues()
    {
    }

    /**
     * Test attribute "dynamic_value"
     */
    public function testPropertyDynamicValue()
    {
    }

    /**
     * Test attribute "file_values"
     */
    public function testPropertyFileValues()
    {
    }

    /**
     * Test attribute "image_values"
     */
    public function testPropertyImageValues()
    {
    }

    /**
     * Test attribute "linked_entity_value"
     */
    public function testPropertyLinkedEntityValue()
    {
    }

    /**
     * Test attribute "ad_value"
     */
    public function testPropertyAdValue()
    {
    }

    /**
     * Test attribute "transaction_value"
     */
    public function testPropertyTransactionValue()
    {
    }

    /**
     * Test attribute "transfer_value"
     */
    public function testPropertyTransferValue()
    {
    }

    /**
     * Test attribute "record_value"
     */
    public function testPropertyRecordValue()
    {
    }

    /**
     * Test attribute "user_value"
     */
    public function testPropertyUserValue()
    {
    }
}
